/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/throne_of_iron__stone.glb 
Author: bossdeff (https://sketchfab.com/bossdeff)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/throne-of-iron-stone-7d55d7464d074e97899afe30aae39dfb
Title: Throne of Iron & Stone
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Throne(props) {
  const { nodes, materials } = useGLTF('models/throne_of_iron__stone.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.BladesTop_BladesTop_0.geometry} material={materials.BladesTop} />
          <mesh geometry={nodes.BladesTop_Swords_0.geometry} material={materials.Swords} />
        </group>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.Swords_Hilt_0.geometry} material={materials.Hilt} />
          <mesh geometry={nodes.Swords_Swords_0.geometry} material={materials.Swords} />
          <mesh geometry={nodes.Swords_SwordsFull_0.geometry} material={materials.SwordsFull} />
        </group>
        <mesh geometry={nodes.BladesBottom_BladesBottom_0.geometry} material={materials.BladesBottom} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.ThroneBaseStone_ThroneStone_0.geometry} material={materials.ThroneStone} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        <mesh geometry={nodes.FabricShall_Fabric_0.geometry} material={materials.Fabric} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      </group>
    </group>
  )
}

useGLTF.preload('models/throne_of_iron__stone.glb')
